import { EnglishMegaHeader } from "@/components/en/EnglishMegaHeader";
import { pdfTools } from "@/data/pdfTools";
import { siteCategories } from "@/data/siteCategories";

const groups = [
  ["Edit & Organize", ["edit-pdf", "pdf-merge", "pdf-split", "rearrange-pdf", "rotate-pdf", "crop-pdf", "pdf-page-deleter"]],
  ["Convert from PDF", ["pdf-to-word", "pdf-to-excel", "pdf-to-powerpoint", "pdf-to-jpg", "pdf-to-png", "pdf-to-text", "pdf-to-csv"]],
  ["Convert to PDF", ["jpg-to-pdf", "png-to-pdf", "word-to-pdf", "powerpoint-to-pdf", "epub-to-pdf", "images-to-pdf", "webp-to-pdf"]],
  ["Protect & Finish", ["compress-pdf", "unlock-pdf", "protect-pdf", "esign-pdf", "add-watermark", "add-numbers-to-pdf", "pdf-translator"]],
] as const;

export function PdfHomePage() {
  const popular = pdfTools.filter((tool) => tool.popular).slice(0, 9);
  return <main className="min-h-screen bg-[#f5f7fb] text-[#263244]"><EnglishMegaHeader />
    <section className="overflow-hidden bg-white"><div className="mx-auto grid min-h-[560px] max-w-[1220px] items-center gap-10 px-5 py-12 lg:grid-cols-[1.1fr_0.9fr]"><div><p className="inline-flex rounded-full bg-[#fff1ec] px-4 py-2 text-sm font-black text-[#ff5b34]">46 free PDF tools</p><h1 className="mt-6 max-w-3xl text-[48px] font-black leading-[1.02] text-[#202b3c] sm:text-[68px] lg:text-[78px]">Everything you need to work with PDF files.</h1><p className="mt-6 max-w-2xl text-lg font-semibold leading-8 text-[#728197]">Edit, merge, split, convert, sign, compress, and extract PDFs. Simple tools run privately in your browser; complex conversions are deleted automatically after one hour.</p><form action="/tools" className="mt-8 flex max-w-2xl gap-2 rounded-full bg-white p-2 shadow-[0_20px_70px_rgba(32,43,60,0.15)] ring-1 ring-[#e7edf5]"><input aria-label="Search PDF tools" className="min-w-0 flex-1 rounded-full bg-[#f7f9fc] px-5 font-bold outline-none" name="q" placeholder="What do you want to do with a PDF?" type="search" /><button className="rounded-full bg-[#ff5b34] px-6 py-3 text-sm font-black text-white" type="submit">Find a tool</button></form></div><div className="relative mx-auto h-[420px] w-full max-w-[460px]"><div className="absolute inset-x-8 top-5 h-[360px] rotate-3 rounded-[36px] bg-[#263244] shadow-[0_34px_90px_rgba(32,43,60,0.25)]" /><div className="absolute inset-x-0 top-10 h-[360px] -rotate-3 rounded-[36px] border border-[#e4ebf3] bg-white p-7 shadow-[0_30px_80px_rgba(32,43,60,0.18)]"><div className="flex items-center justify-between"><span className="grid h-14 w-14 place-items-center rounded-[18px] bg-[#fff1ee] font-black text-[#ff5b34]">PDF</span><span className="rounded-full bg-[#eef9f3] px-3 py-2 text-xs font-black text-[#269564]">Browser private</span></div><div className="mt-8 h-4 w-3/4 rounded bg-[#e8edf4]" /><div className="mt-4 h-3 w-full rounded bg-[#f0f3f7]" /><div className="mt-3 h-3 w-5/6 rounded bg-[#f0f3f7]" /><div className="mt-10 grid grid-cols-2 gap-3">{["Merge", "Convert", "Sign", "Compress"].map((label) => <div className="rounded-[16px] bg-[#f7f9fc] p-4 text-center text-sm font-black" key={label}>{label}</div>)}</div></div></div></div></section>
    <section className="border-y border-[#e7edf5] bg-[#f5f7fb]"><div className="mx-auto grid max-w-[1220px] grid-cols-2 gap-px bg-[#e7edf5] sm:grid-cols-3 lg:grid-cols-5">{siteCategories.map((category) => <a className="bg-white px-5 py-6 hover:bg-[#fbfcfe]" href={category.href} key={category.slug}><span className="text-xs font-black uppercase text-[#8a98aa]">{category.availableCount} available</span><span className="mt-2 block text-xl font-black">{category.name} Tools</span><span className="mt-2 block text-sm font-semibold text-[#728197]">{category.targetCount} mapped tools</span></a>)}</div></section>
    <section className="mx-auto max-w-[1220px] px-5 py-14"><div className="text-center"><h2 className="text-[38px] font-black">Most popular PDF tools</h2><p className="mt-3 font-semibold text-[#728197]">Start with the tasks people use every day.</p></div><div className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{popular.map((tool) => <a className="group flex gap-4 rounded-[22px] border border-[#e7edf5] bg-white p-5 shadow-[0_8px_24px_rgba(32,43,60,0.05)] hover:border-[#ffc3b4]" href={`/tools/${tool.slug}`} key={tool.slug}><span className="grid h-14 w-14 shrink-0 place-items-center rounded-[18px] bg-[#fff1ee] text-xs font-black text-[#ef5535]">{tool.icon}</span><span><span className="font-black group-hover:text-[#ff5b34]">{tool.name}</span><span className="mt-2 block text-sm font-semibold leading-6 text-[#728197]">{tool.description}</span></span></a>)}</div></section>
    <section className="bg-white py-14"><div className="mx-auto max-w-[1220px] px-5"><div className="flex items-end justify-between"><div><h2 className="text-[38px] font-black">Browse by task</h2><p className="mt-3 font-semibold text-[#728197]">A focused toolkit for every stage of a PDF workflow.</p></div><a className="text-sm font-black text-[#ff5b34]" href="/tools">View all 46</a></div><div className="mt-8 grid gap-5 md:grid-cols-2">{groups.map(([title, slugs]) => <section className="rounded-[24px] bg-[#f7f9fc] p-6" key={title}><h3 className="text-xl font-black">{title}</h3><div className="mt-5 grid gap-2 sm:grid-cols-2">{slugs.map((slug) => { const tool = pdfTools.find((item) => item.slug === slug); return tool ? <a className="rounded-[14px] bg-white px-4 py-3 text-sm font-black hover:text-[#ff5b34]" href={`/tools/${tool.slug}`} key={slug}>{tool.name}</a> : null; })}</div></section>)}</div></div></section>
    <footer className="border-t border-[#e7edf5] bg-white"><div className="mx-auto flex max-w-[1220px] flex-col gap-5 px-5 py-9 sm:flex-row sm:items-center sm:justify-between"><div className="font-black">TOOLMOMO <span className="ml-2 text-sm font-semibold text-[#728197]">Private browser tools and secure conversions</span></div><div className="flex flex-wrap gap-5 text-sm font-bold text-[#728197]"><a href="/tools">PDF</a><a href="/tools/image">Image</a><a href="/privacy">Privacy</a><a href="/contact">Contact</a><a href="/disclaimer">Disclaimer</a></div></div></footer>
  </main>;
}
