import { AdSenseUnit } from "@/components/ads/AdSenseUnit";
import { EnglishMegaHeader } from "@/components/en/EnglishMegaHeader";
import { pdfTools } from "@/data/pdfTools";
import { imageTools } from "@/data/imageTools";
import { writeTools } from "@/data/writeTools";
import { videoTools } from "@/data/videoTools";
import { fileTools } from "@/data/fileTools";
import { siteCategories } from "@/data/siteCategories";

const popular = [
  ...pdfTools.filter((tool) => tool.popular).slice(0, 4).map((tool) => ({ ...tool, href: `/tools/${tool.slug}`, category: "PDF", color: "#ff5b34", background: "#fff1ee" })),
  ...imageTools.filter((tool) => tool.popular).slice(0, 3).map((tool) => ({ ...tool, href: `/tools/image/${tool.slug}`, category: "Image", color: "#147d78", background: "#e9f8f6" })),
  ...writeTools.filter((tool) => tool.provider === "openai").slice(0, 2).map((tool) => ({ ...tool, href: `/tools/write/${tool.slug}`, category: "Write", color: "#6842b5", background: "#f1ebfc" })),
];

export function PdfHomePage() {
  return <main className="min-h-screen bg-[#f5f7fb] text-[#263244]"><EnglishMegaHeader />
    <section className="overflow-hidden bg-white"><div className="mx-auto grid min-h-[540px] max-w-[1220px] items-center gap-10 px-5 py-12 lg:grid-cols-[1.08fr_0.92fr]"><div><p className="inline-flex rounded-full bg-[#fff1ec] px-4 py-2 text-sm font-black text-[#ff5b34]">243 practical online tools</p><h1 className="mt-6 max-w-3xl text-[48px] font-black leading-[1.02] text-[#202b3c] sm:text-[68px] lg:text-[76px]">One place to finish everyday digital work.</h1><p className="mt-6 max-w-2xl text-lg font-semibold leading-8 text-[#728197]">Edit PDFs, improve images, write with AI, convert video and audio, and transform files. Local tools stay in your browser; remote files are deleted automatically.</p><form action="/tools" className="mt-8 flex max-w-2xl gap-2 rounded-full bg-white p-2 shadow-[0_20px_70px_rgba(32,43,60,0.15)] ring-1 ring-[#e7edf5]"><input aria-label="Search all tools" className="min-w-0 flex-1 rounded-full bg-[#f7f9fc] px-5 font-bold outline-none" name="q" placeholder="What do you want to do?" type="search" /><button className="rounded-full bg-[#ff5b34] px-6 py-3 text-sm font-black text-white" type="submit">Find a tool</button></form></div><div className="relative mx-auto h-[420px] w-full max-w-[460px]"><div className="absolute inset-x-8 top-5 h-[360px] rotate-3 rounded-[28px] bg-[#263244] shadow-[0_34px_90px_rgba(32,43,60,0.25)]" /><div className="absolute inset-x-0 top-10 h-[360px] -rotate-3 rounded-[28px] border border-[#e4ebf3] bg-white p-7 shadow-[0_30px_80px_rgba(32,43,60,0.18)]"><div className="flex items-center justify-between"><span className="grid h-14 w-14 place-items-center rounded-[14px] bg-[#fff1ee] font-black text-[#ff5b34]">T</span><span className="rounded-full bg-[#eef9f3] px-3 py-2 text-xs font-black text-[#269564]">Private when possible</span></div><div className="mt-8 h-4 w-3/4 rounded bg-[#e8edf4]" /><div className="mt-4 h-3 w-full rounded bg-[#f0f3f7]" /><div className="mt-3 h-3 w-5/6 rounded bg-[#f0f3f7]" /><div className="mt-10 grid grid-cols-2 gap-3">{["PDF", "Image", "Write", "Video"].map((label) => <div className="rounded-[12px] bg-[#f7f9fc] p-4 text-center text-sm font-black" key={label}>{label}</div>)}</div></div></div></div></section>
    <section className="mx-auto max-w-[1220px] px-5 py-10"><AdSenseUnit slot={process.env.NEXT_PUBLIC_ADSENSE_HOME_SLOT} /></section>
    <section className="border-y border-[#e7edf5] bg-white"><div className="mx-auto grid max-w-[1220px] grid-cols-2 gap-px bg-[#e7edf5] sm:grid-cols-3 lg:grid-cols-5">{siteCategories.map((category) => <a className="bg-white px-5 py-6 hover:bg-[#fbfcfe]" href={category.href} key={category.slug}><span className="text-xs font-black uppercase" style={{ color: category.accent }}>{category.availableCount} tools</span><span className="mt-2 block text-xl font-black">{category.name}</span><span className="mt-2 block text-sm font-semibold text-[#728197]">Browse all {category.name.toLowerCase()} utilities</span></a>)}</div></section>
    <section className="mx-auto max-w-[1220px] px-5 py-14"><div className="flex items-end justify-between gap-5"><div><h2 className="text-[38px] font-black">Popular tools</h2><p className="mt-3 font-semibold text-[#728197]">Useful starting points across the TOOLMOMO catalog.</p></div><a className="text-sm font-black text-[#ff5b34]" href="/tools">Browse all 243</a></div><div className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{popular.map((tool) => <a className="group flex gap-4 rounded-[18px] border border-[#e7edf5] bg-white p-5 shadow-[0_8px_24px_rgba(32,43,60,0.05)] hover:border-[#ffc3b4]" href={tool.href} key={tool.href}><span className="grid h-14 w-14 shrink-0 place-items-center rounded-[14px] text-xs font-black" style={{ background: tool.background, color: tool.color }}>{tool.icon}</span><span><span className="text-xs font-black uppercase text-[#9aa7b8]">{tool.category}</span><span className="mt-1 block font-black group-hover:text-[#ff5b34]">{tool.name}</span><span className="mt-2 block text-sm font-semibold leading-6 text-[#728197]">{tool.description}</span></span></a>)}</div></section>
    <section className="bg-white py-14"><div className="mx-auto max-w-[1220px] px-5"><h2 className="text-[38px] font-black">Built around your privacy</h2><div className="mt-8 grid gap-6 md:grid-cols-3"><div><h3 className="text-lg font-black">Browser-first</h3><p className="mt-2 text-sm font-semibold leading-7 text-[#728197]">Common PDF, image, text, and structured-data tasks run locally on your device.</p></div><div><h3 className="text-lg font-black">Short-lived conversions</h3><p className="mt-2 text-sm font-semibold leading-7 text-[#728197]">Remote conversion files use random job IDs and are deleted automatically after one hour.</p></div><div><h3 className="text-lg font-black">Clear limits</h3><p className="mt-2 text-sm font-semibold leading-7 text-[#728197]">Tool pages explain supported formats, processing mode, file limits, and provider use before you start.</p></div></div></div></section>
    <footer className="border-t border-[#e7edf5] bg-white"><div className="mx-auto flex max-w-[1220px] flex-col gap-5 px-5 py-9 sm:flex-row sm:items-center sm:justify-between"><div className="font-black">TOOLMOMO <span className="ml-2 text-sm font-semibold text-[#728197]">243 practical online tools</span></div><div className="flex flex-wrap gap-5 text-sm font-bold text-[#728197]"><a href="/tools">All Tools</a><a href="/privacy">Privacy</a><a href="/contact">Contact</a><a href="/disclaimer">Disclaimer</a></div></div></footer>
  </main>;
}
