type RelatedTool = { name: string; description: string; href: string; icon: string };
type ToolDetailsProps = { name: string; category: string; mode: "browser" | "ai" | "remote"; formats?: string; related: RelatedTool[]; note?: string };

export function ToolDetails({ name, category, mode, formats, related, note }: ToolDetailsProps) {
  const modeText = mode === "browser" ? "This tool runs in your browser. Your source file or text is not uploaded to TOOLMOMO." : mode === "ai" ? "Your text is sent securely to the configured AI provider. TOOLMOMO does not keep a writing history." : "Your file is uploaded for secure conversion and the temporary input and result are deleted after one hour.";
  return <>
    <section className="border-y border-[#e4eaf1] bg-white"><div className="mx-auto grid max-w-[1100px] gap-10 px-5 py-14 lg:grid-cols-2"><div><h2 className="text-2xl font-black">How to use {name}</h2><ol className="mt-5 grid gap-4 text-sm font-semibold leading-7 text-[#66758a]"><li><strong className="text-[#263244]">1. Add your input.</strong> Choose the requested file or enter the text and instructions.</li><li><strong className="text-[#263244]">2. Review the options.</strong> Set the available format, quality, dimensions, tone, or processing preferences.</li><li><strong className="text-[#263244]">3. Run and download.</strong> Process the task, review the result, and download or copy it when ready.</li></ol>{note ? <p className="mt-5 border-l-4 border-[#ff5b34] pl-4 text-sm font-semibold leading-7 text-[#66758a]">{note}</p> : null}</div><div><h2 className="text-2xl font-black">Limits and privacy</h2><dl className="mt-5 grid gap-4 text-sm"><div><dt className="font-black">Processing</dt><dd className="mt-1 font-semibold leading-7 text-[#66758a]">{modeText}</dd></div><div><dt className="font-black">Supported input</dt><dd className="mt-1 font-semibold leading-7 text-[#66758a]">{formats || "The formats shown in the upload field."}</dd></div><div><dt className="font-black">Limits</dt><dd className="mt-1 font-semibold leading-7 text-[#66758a]">Files are limited to 50 MB. PDF jobs are limited to 100 pages. Complex and AI tools allow five jobs per IP each UTC day.</dd></div></dl></div></div></section>
    <section className="mx-auto max-w-[1100px] px-5 py-14"><h2 className="text-2xl font-black">Frequently asked questions</h2><div className="mt-5 divide-y divide-[#e4eaf1] border-y border-[#e4eaf1]"><details className="py-5"><summary className="cursor-pointer font-black">Is {name} free?</summary><p className="mt-3 text-sm font-semibold leading-7 text-[#66758a]">Yes. Browser tools have no usage limit. Complex provider and AI tools have a daily fair-use limit while TOOLMOMO uses provider quotas.</p></details><details className="py-5"><summary className="cursor-pointer font-black">Does TOOLMOMO store my files?</summary><p className="mt-3 text-sm font-semibold leading-7 text-[#66758a]">Browser tools do not upload files. Remote jobs use temporary storage and are deleted automatically after one hour.</p></details><details className="py-5"><summary className="cursor-pointer font-black">What should I do if processing fails?</summary><p className="mt-3 text-sm font-semibold leading-7 text-[#66758a]">Check the file format and size, retry once, then use a smaller or unencrypted source file. Provider quotas or unsupported file variants can also cause failures.</p></details></div></section>
    {related.length ? <section className="bg-[#f5f7fb]"><div className="mx-auto max-w-[1100px] px-5 py-14"><h2 className="text-2xl font-black">Related {category} tools</h2><div className="mt-6 grid gap-4 md:grid-cols-3">{related.slice(0, 3).map((tool) => <a className="flex gap-3 rounded-[12px] border border-[#e4eaf1] bg-white p-4 hover:border-[#ffb5a2]" href={tool.href} key={tool.href}><span className="grid h-11 w-11 shrink-0 place-items-center rounded-[10px] bg-[#f2f5f8] text-[10px] font-black">{tool.icon}</span><span><span className="font-black">{tool.name}</span><span className="mt-1 block text-xs font-semibold leading-5 text-[#728197]">{tool.description}</span></span></a>)}</div></div></section> : null}
  </>;
}
